version: 2.1
jobs:
  mocap_processing:
    resource_class: xlarge
    docker:
      - image: ros:kinetic-robot-xenial
      
    steps:
      - checkout            
      - run:
          name: Install mocap_processing
          command: |
            cd ~/project
            sudo apt-get install python3-pip
            sudo pip3 install virtualenv 
            virtualenv --python=python3 ./mocap_processing_env
            source ./mocap_processing_env/bin/activate
            pip install -e .
      - run:
          name: Run Tests
          command: |
            cd ~/project
            source ./mocap_processing_env/bin/activate
            python setup.py test

workflows:
  version: 2
  install_and_test:
    jobs:
      - mocap_processing